---
# tasks file for roles/launch_proxy

- name: Pull the proxy container
  docker_image:
    name: justinesmmt/tp-devops-simple-api-httpd
    tag: latest
    source: pull
 
- name: Run the proxy container
  docker_container:
    name: httpd-1
    image: justinesmmt/tp-devops-simple-api-httpd
    ports:
      - "80:80"
    networks:
      - name: "app-network"